#!/usr/bin/env sh

YEAR=`date +%Y`
opensource_dir=`dirname $0`
config_dir=$opensource_dir/config/
licenses_dir=$opensource_dir/licenses/
source $config_dir/*

# Displays the given input
log() {
  echo -e "$@" >&2
}

# Create license file
create_license() {
  local license=$1
  local path=`cd $2; pwd`
  if test $# -eq 2; then
    echo "$license" > $path/LICENSE
  elif test $# -eq 1; then
    echo "$license" > LICENSE
  else
    echo "Please refer opensource -h for the right usage."
  fi
}


# Called in case of error
error_exit() {
  echo "Error: $1"
  exit 1
}

require() {
  which $1 > /dev/null || error_exit "$0 requires $1"
}

help() {
  log "Help:

  USAGE

    opensource [options] [/path/to/project/]

  DESCRIPTION

    OpenSource is a tiny shell script that allows you to add the type of license
    you wish to add to your project.

  OPTIONS

    -h, --help
        Show this help information.

    -l, --license
        Mention the type of license you want to add to your project.
        usage: opensource -l mit
  "
}

# TODO: Add a safety filter for `YEAR` and `EMAIL` variables
# If `EMAIL` is not set, then the angular brackets should not be
# displayed.

# Flags
if test "$1" = "-h" -o "$1" = "--help"; then
  help
  exit 0
elif test "$#" -eq 2 -a "$1" = "-l" -a "$2" = "mit"; then
  source $licenses_dir/mit.sh
  log "$MIT"
  create_license "$MIT"
  exit 0
elif test "$#" -eq 3 -a "$1" = "-l" -a "$2" = "mit"; then
  source $licenses_dir/mit.sh
  log "$MIT"
  create_license "$MIT" "$3"
  exit 0
else
  echo "Please refer help for usage instructions. opensource -h or opensource --help"
  exit 0
fi